# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

brand: lloyds
journeyName: starter-kit
valuestream: vbp

# image to deploy
image:
  baseRepository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# roleBinding is required as clusters have pod-security-policy enabled
roleBinding:
  enabled: true
  roleRefName: psp:restrictive
  kind: "" # defaults to ClusterRole
  # Annotations to add to the role binding
  annotations: {}

# probes used to check web server health status
healthProbes:
  livenessPath: /
  readinessPath: /

# kubernetes service
service:
  type: ClusterIP
  port: 80
  containerPort: 8080

# ingress
ingress:
  enabled: true
  className: nginx
  extraAnnotations: {}
    # nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
  hostNameOverride: ""
  # hostNameOverride: minikube
  rootSubdomain: ""
  # rootSubdomain: interstellar-sdk
  prSubdomain: ""
  # prSubdomain: 'pr-xxx'
  pathType: ImplementationSpecific
  tlsSecretName: ""
  # tlsSecretName: chart-example-tls
  # optional vars #
  pathPrefix: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# adds extra envrionment variables into the container by dumping yaml into template
# on GCP secrets should be consumed via Google Secret Manager (GSM)
envVars: {}
  # envFrom:
  #   - secretRef:
  #       name: secret-name
  # env:
  #   - name: VAR_NAME
  #     value: VAR_VALUE
  #   - name: NODE_NAME
  #     valueFrom:
  #       fieldRef:
  #         fieldPath: spec.nodeName
  #   - name: SECRET_NAME
  #     valueFrom:
  #       secretKeyRef:
  #         name: secret-name
  #         key: secret-key

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000
  # runAsUser: 200

securityContext:
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true
  # allowPrivilegeEscalation: false
  # runAsNonRoot: false
  # runAsUser: 1000

# securityContext:
#   allowPrivilegeEscalation: true
#   runAsNonRoot: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
